language: c++

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.8
            - g++-4.8
            - wget
            # Package list from http://bazel.io/docs/install.html
            - openjdk-7-jdk
            - openjdk-7-source
            - pkg-config
            - zip
            - zlib1g-dev
    - os: osx
      osx_image: xcode7.3

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget 'https://github.com/bazelbuild/bazel/releases/download/0.2.3/bazel-0.2.3-installer-darwin-x86_64.sh' ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then chmod +x bazel-0.2.3-installer-darwin-x86_64.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./bazel-0.2.3-installer-darwin-x86_64.sh --user ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget 'https://github.com/bazelbuild/bazel/releases/download/0.2.3/bazel-0.2.3-installer-linux-x86_64.sh' ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod +x bazel-0.2.3-installer-linux-x86_64.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./bazel-0.2.3-installer-linux-x86_64.sh --user ; fi
  - cat .bazelrc_travis_patch > .bazelrc
  - cat ~/.bazelrc >> .bazelrc

script:
  - bazel build //:lemonscript
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xctool test -project lemonscript.xcodeproj -scheme lemonscript_tests ; fi

after_script:
  - rm .bazelrc
